title: Wenyuan Deng
description: Academic homepage of Wenyuan Deng
theme: minima

author:
  name: Wenyuan Deng

github_username: wenyuan14

header_pages:
  - research-log.md
  - projects.md
  - study-notes.md
